=== omarhassanhub/Reveryreview-Blog/bookschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://localhost"
  xmlns="http://localhost"
  elementFormDefault="qualified">

<xs:element name="books">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="book" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="title" type="bookTitle" />
                        <xs:element name="edition" type="xs:unsignedByte" minOccurs="0" maxOccurs="1" />
                        <xs:element name="type" type="bookType" />
                        <xs:element name="price" type="price" />
						<xs:element name="bookImage" type="bookImage" />
						<xs:element name="firstParagraph" type="firstParagraph" />
						<xs:element name="secondParagraph" type="secondParagraph" />
                        <xs:element name="author" type="fullAuthorName" minOccurs="1" maxOccurs="unbounded" />
                        <xs:element name="publishedDate" type="complexDate" />
						<xs:element name="contributor" type="fullContributorName" minOccurs="1" maxOccurs="unbounded" />
                    </xs:sequence>
                    <xs:attribute name="isbn" type="isbnType" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:simpleType name="isbnType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{10}"/>
    </xs:restriction>
  </xs:simpleType>

<xs:element name="book">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="isbn" type="isbnType"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

<xs:simpleType name = "bookTitle">
    <xs:restriction base="xs:string">
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="fullAuthorName">
    <xs:sequence>
        <xs:element name="first" type="xs:string" />
        <xs:element name="middle" minOccurs="0" maxOccurs="1">
            <xs:simpleType>    
                <xs:restriction base="xs:string">
                    <xs:minLength value="0"/>
					<xs:maxLength value="20"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
        <xs:element name="last" type="xs:string" />
    </xs:sequence>
</xs:complexType>

<xs:complexType name = "complexDate">
    <xs:sequence>
        <xs:element name="day">
            <xs:simpleType>
                <xs:restriction base="xs:unsignedByte">
                    <xs:minInclusive value="1" />
                    <xs:maxInclusive value="31" />
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
      <xs:element name="month">
            <xs:simpleType>
                <xs:restriction base="xs:unsignedByte">
                    <xs:minInclusive value="1" />
                    <xs:maxInclusive value="12" />
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
        
        <xs:element name="year" type="xs:gYear" />
    </xs:sequence>
</xs:complexType>

<xs:simpleType name = "bookType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="Programming Language" />
        <xs:enumeration value="non-Programming Language" />
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name = "price">
    <xs:restriction base="xs:decimal">
        <xs:totalDigits value="5" />
        <xs:fractionDigits value="2" />
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="fullContributorName">
    <xs:sequence>
        <xs:element name="contFirst" type="xs:string" />
        <xs:element name="contMiddle" minOccurs="0" maxOccurs="1">
            <xs:simpleType>    
                <xs:restriction base="xs:string">
                    <xs:maxLength value="1" />
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
        <xs:element name="contLast" type="xs:string" />
		<xs:element name="postedDate"> <!-- type="xs:date" !-->
		<xs:simpleType>    
                
			    <xs:restriction base="xs:string">
			        <xs:pattern value="([0-9]{2}/){2}[0-9]{4}"/>
			    </xs:restriction>
			</xs:simpleType>
        </xs:element>
		
    </xs:sequence>

</xs:complexType>

	<xs:complexType name="bookImage">
    <xs:simpleContent>
        <xs:extension base="xs:string">
            <xs:attribute name="type">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="PNG" />
                        <xs:enumeration value="JPG" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>

<xs:simpleType name = "firstParagraph">
    <xs:restriction base="xs:string">
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name = "secondParagraph">
    <xs:restriction base="xs:string">
    </xs:restriction>
</xs:simpleType>

</xs:schema>

=== omarhassanhub/Reveryreview-Blog/bookxml.xml
<?xml version="1.0"?>
<books xmlns="http://localhost" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://localhost bookschema.xsd">
  <!--!DOCTYPE books SYSTEM "bookdtd.dtd"!-->
  <book isbn="0836217462">
    <title>Imperfect C++</title>
    <edition>1</edition>
    <type>Programming Language</type>
    <price>16.00</price>
    <bookImage type="JPG">images/imperfectc++.jpg</bookImage>
    <firstParagraph>
      C++ is not a perfect language and Matthew Wilson tries to explain how to put it right. This book outlines the author&#x2019;s views on how to program in C++ and how to best use C++ and is full of academic references and quotes from other people&#x2019;s work.
    </firstParagraph>
    <secondParagraph>
      The first few pages are persuasive, as soon as I got started, alot of difficult concepts are introduced. Templates and a lot of advanced features are being used without any description and you either understand the examples or you don&#x2019;t. The examples are more related with scholarly philosophy. Even if you do understand everything about C++ you will still be left with an overwhelming feeling that maybe C++ is just too flawed as a language.

      C was a good language in its time, which was a high level assembler. However, C++ is perhaps best described as a low level object-oriented language. You can use it to create anything you want to make it and as such over all the language has no regulation.
      This book is about introducing regulation into its readers when the fault lies in the language. Personally, I think this book is for super experts, but it isn&#x2019;t for the general reader.
    </secondParagraph>
    <author>
      <first>Matthew</first>
      <middle/>
      <last>Wilson</last>
    </author>
    <publishedDate>
      <day>21</day>
      <month>10</month>
      <year>2004</year>
    </publishedDate>
    <contributor>
      <contFirst>Omar</contFirst>
      <contMiddle/>
      <contLast>Hassan</contLast>
      <postedDate>15/11/2014</postedDate>
    </contributor>
  </book>
  <book isbn="0132821540">
    <title>Java for Programmers</title>
    <edition>1</edition>
    <type>Programming Language</type>
    <price>36.43</price>
    <bookImage type="JPG">images/Java4Programmers.jpg</bookImage>
    <firstParagraph>
	I wasn't really interested with this book. The Deitel approach is to create something enormous such as an academic textbook than an inspiring read. It has 1200 pages. It is a very friendly and helpful by including short notes on usual mistakes in programming. Though the layout and the very small print probably make the effort pointless.
	</firstParagraph>
    <secondParagraph>
	It covers Java 6 from the first concepts including objects, widgets, user interface, JDBC, graphics, generics and so on. 
	Though it is supposedly aimed at programmers, but it is not a great book for a beginner because the order in which the material is initiated isn't helpful and nor is the introduction of advanced concepts such as object oriented design and UML right at the start. 

	The authors really do not seem to have a clear idea of who their audience is and as a result have ended up making a book that is not exactly right for any level of experience. The best thing I can state about this book is that it's "very big".
	</secondParagraph>
    <author>
      <first>Paul </first>
      <middle/>
      <last>Deitel</last>
    </author>
    <publishedDate>
      <day>12</day>
      <month>02</month>
      <year>2009</year>
    </publishedDate>
    <contributor>
      <contFirst>Ramal</contFirst>
      <contMiddle/>
      <contLast>Sayi</contLast>
      <postedDate>19/11/2014</postedDate>
    </contributor>
  </book>
  <book isbn="0596527748">
    <title>Head First JavaScript</title>
    <edition>1</edition>
    <type>Programming Language</type>
    <price>25.72</price>
    <bookImage type="JPG">images/head_first_javascript.jpg</bookImage>
    <firstParagraph>
	Head First books are thought to make difficult subjects easy but just rarely you have to come to the decision that trivializing a difficult idea is not really a good idea. In this case the topic matter is JavaScript, a computer language embedded in a very complex environment - HTML, DOM, and just about everything else you can name. What makes the condition worse is that there is no good development environment. In brief JavaScript can be very difficult.
	</firstParagraph>
    <secondParagraph>
	
	The method used by all books in the Head First series is labelled as brain friendly and uses a mixture of quizzes, photos, notes with captions and jokes to make learning easy. This specific one just doesn't work. The presentation is random and achieves its brain-friendly status by simply going slow and throwing in exercises as if their purpose was to decrease the pace and so make it all so much easier. 
	
	It also reads as if it has been set together in a rush and not well thought out.There are many times when I really disagree with the ideas being presented - for example if statements as an alternative to using logical conditions.
	</secondParagraph>
    <author>
      <first>Michael </first>
      <middle/>
      <last>Morrison</last>
    </author>
    <publishedDate>
      <day>30</day>
      <month>12</month>
      <year>2007</year>
    </publishedDate>
    <contributor>
      <contFirst>Emily</contFirst>
      <contMiddle/>
      <contLast>Dave</contLast>
      <postedDate>21/11/2014</postedDate>
    </contributor>
  </book>
  <book isbn="0470413964">
    <title>Beginning PHP 5.3</title>
    <edition>1</edition>
    <type>Programming Language</type>
    <price>26.99</price>
    <bookImage type="JPG">images/beginningphp.jpg</bookImage>
    <firstParagraph>
	This is a straightforward method to explaining PHP with the first eight chapters following a standard course through the material. The details are clear, sometimes a little too much for the complete beginner, and the examples are to the point. By the end of Chapter 8, you reach objects and object-oriented methods.
	</firstParagraph>
    <secondParagraph>
	The remaining of the book is a section titled &#x201C;Using PHP in Practice&#x201D; and this focuses with all of the methods that PHP interacts with other web technologies. The book clarifies how to control forms, and work with files and offers three whole chapters regarding MySQL database. 
	
	From this section, the book begins to cover the restrictions of the PHP world, working with XML, images, regular expressions, and writing high quality code. Though much of the book is appropriate for the beginner the technical level does increase steadily but the concepts are well described. 
	</secondParagraph>
    <author>
      <first>Matt</first>
      <middle/>
      <last>Doyle</last>
    </author>
    <publishedDate>
      <day>27</day>
      <month>10</month>
      <year>2009</year>
    </publishedDate>
    <contributor>
      <contFirst>Omar</contFirst>
      <contMiddle/>
      <contLast>Hassan</contLast>
      <postedDate>05/12/2014</postedDate>
    </contributor>
  </book>
  <book isbn="0470563125">
    <title>Expert PHP and MySQL</title>
    <edition>1</edition>
    <type>Programming Language</type>
    <price>20.39</price>
    <bookImage type="JPG">images/phpmysql.jpg</bookImage>
    <firstParagraph>
	This book targets to take someone who understands the basics of PHP programming, and show them not just how to create PHP and MySQL projects, but how to construct projects. 
    Marc Rochkind technical background is inspiring, and that shows through in this well-written book.
	</firstParagraph>
    <secondParagraph>
	The chapter one is mainly focused on project organisation covering subjects such as setting the schedule, creating a development team, reasons why projects fail, authorities such as having a written contract, invoicing and getting the money, and intellectual rights.
	
    Chapter two moves on to requirements in regards to the requirements document, ways to deal with requirements changing, managing the project scope, and agile requirements. Though all of this is common to all software projects, but fascinating reading all the same.
	</secondParagraph>
    <author>
      <first>Marc</first>
      <middle/>
      <last>Rochkind</last>
    </author>
    <publishedDate>
      <day>19</day>
      <month>03</month>
      <year>2010</year>
    </publishedDate>
    <contributor>
      <contFirst>Omar</contFirst>
      <contMiddle/>
      <contLast>Hassan</contLast>
      <postedDate>15/12/2014</postedDate>
    </contributor>
  </book>
  <book isbn="1935182080">
    <title>Hello! Python </title>
    <edition>1</edition>
    <type>Programming Language</type>
    <price>20.44</price>
    <bookImage type="JPG">images/python.jpg</bookImage>
    <firstParagraph>
	Chapter 1 begins us off with the ways to find and setup Python on Mac, Windows and Linux. The guidelines are clear, but when it comes to testing the installation we have to resort to a text editor and to the command prompt. 
	</firstParagraph>
    <secondParagraph>
	Chapter 2 presents Python through an example &#x201C; Wumpus&#x201D; program. This begins by presenting the print statement with &#x201C;Hello World&#x201D; but 4 pages on we have looked at variables and loops. 
	
	For instance, variables are labelled as being able of storing floating point values, however, this is not a term that is described and not one that a beginner is expected to have encountered.
	
	The method to teaching seems to be to tell the reader as much as possible and display it in action in a reasonably difficult program example. 
	If this is how a learner wants to learn, then they will like this book but most complete beginners are going to be left questioning what is going on.
	</secondParagraph>
    <author>
      <first>Anthony </first>
      <middle/>
      <last>Briggs</last>
    </author>
    <publishedDate>
      <day>23</day>
      <month>02</month>
